export const COUNTRIES_PL = {
  ie: {
    name: "Irlandia",
    locative: "Irlandii",
    subdomain: "ie",
    flag: "/flags/ie.png",
    capital: "Dublin",
    lat: 53.35,
    lon: -6.26,
    timezone: "Europe/Dublin",
    currency: "€",
  },
  de: {
    name: "Niemcy",
    locative: "Niemczech",
    subdomain: "de",
    flag: "/flags/de.png",
    capital: "Berlin",
    lat: 52.52,
    lon: 13.41,
    timezone: "Europe/Berlin",
    currency: "€",
  },
  es: {
    name: "Hiszpania",
    locative: "Hiszpanii",
    subdomain: "es",
    flag: "/flags/es.png",
    capital: "Madryt",
    lat: 40.42,
    lon: -3.7,
    timezone: "Europe/Madrid",
    currency: "€",
  },
  fr: {
    name: "Francja",
    locative: "Francji",
    subdomain: "fr",
    flag: "/flags/fr.png",
    capital: "Paryż",
    lat: 48.85,
    lon: 2.35,
    timezone: "Europe/Paris",
    currency: "€",
  },
  it: {
    name: "Włochy",
    locative: "Włoszech",
    subdomain: "it",
    flag: "/flags/it.png",
    capital: "Rzym",
    lat: 41.9,
    lon: 12.49,
    timezone: "Europe/Rome",
    currency: "€",
  },
  nl: {
    name: "Holandia",
    locative: "Holandii",
    subdomain: "nl",
    flag: "/flags/nl.png",
    capital: "Amsterdam",
    lat: 52.37,
    lon: 4.9,
    timezone: "Europe/Amsterdam",
    currency: "€",
  },
  se: {
    name: "Szwecja",
    locative: "Szwecji",
    subdomain: "se",
    flag: "/flags/se.png",
    capital: "Sztokholm",
    lat: 59.33,
    lon: 18.07,
    timezone: "Europe/Stockholm",
    currency: "kr",
  },
  no: {
    name: "Norwegia",
    locative: "Norwegii",
    subdomain: "no",
    flag: "/flags/no.png",
    capital: "Oslo",
    lat: 59.91,
    lon: 10.75,
    timezone: "Europe/Oslo",
    currency: "kr",
  },
  uk: {
    name: "Wielka Brytania",
    locative: "Wielkiej Brytanii",
    subdomain: "gb",
    flag: "/flags/gb.png",
    capital: "Londyn",
    lat: 51.51,
    lon: -0.13,
    timezone: "Europe/London",
    currency: "£",
  },
  pl: {
    name: "Polska",
    locative: "Polsce",
    subdomain: "pl",
    flag: "/flags/pl.png",
    capital: "Warszawa",
    lat: 52.23,
    lon: 21.01,
    timezone: "Europe/Warsaw",
    currency: "zł",
  },
};
